### ISSUE TITLE
No matching use for vue-loader is found

### ISSUE THREAD

**Issue by hmuhdkamran** [Jamie-Yang/vue3-boilerplate#2] opened 2020-06-23 02:46 UTC
I have simply clone this and use the following steps.
1. npm i
2. npm run serve
and it generate the following error
`E:\test\Vue3\vue3-boilerplate\node_modules\vue-loader\dist\pluginWebpack5.js:68
            throw new Error(`[VueLoaderPlugin Error] No matching use for vue-loader is found.\n` +
            ^

Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (E:\test\Vue3\vue3-boilerplate\node_modules\vue-loader\dist\pluginWebpack5.js:68:19)
    at createCompiler (E:\test\Vue3\vue3-boilerplate\node_modules\webpack\lib\webpack.js:70:12)
    at webpack (E:\test\Vue3\vue3-boilerplate\node_modules\webpack\lib\webpack.js:113:14)
    at f (E:\test\Vue3\vue3-boilerplate\node_modules\webpack\lib\index.js:31:15)
    at Object.<anonymous> (E:\test\Vue3\vue3-boilerplate\service\commands\serve.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue3-boilerplate@1.0.0 serve: `node service/commands/serve.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue3-boilerplate@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\H.Muhammad Kamran\AppData\Roaming\npm-cache\_logs\2020-06-23T02_43_46_492Z-debug.log`

**Comment by Jamie-Yang** [comment] 2020-06-23 15:56
This issue is caused by vue-loader@next, and my PR has been merged today. https://github.com/vuejs/vue-loader/pull/1680
Now it should have been solved.

**Closed by Jamie-Yang** 2020-06-23 15:56 UTC
